extends: "eslint:recommended"
env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2017
rules:
  array-callback-return: "error"
  block-scoped-var: "error"
  curly: "error"
  default-case: "error"
  dot-location:
    - "error"
    - "property"
  dot-notation: "error"
  eqeqeq: "error"
  guard-for-in: "error"
  no-alert: "error"
  no-caller: "error"
  no-else-return: "error"
  no-empty-function: "error"
  no-eval: "error"
  no-extend-native: "error"
  no-extra-bind: "error"
  no-floating-decimal: "error"
  no-implicit-coercion:
    - "error"
    - allow:
      - "!!"
  no-implicit-globals: "error"
  no-implied-eval: "error"
  no-invalid-this: "off"
  no-iterator: "error"
  no-labels: "error"
  no-lone-blocks: "error"
  no-loop-func: "error"
  no-multi-spaces: "error"
  no-multi-str: "error"
  no-native-reassign: "error"
  no-new: "error"
  no-new-wrappers: "error"
  no-octal-escape: "error"
  no-proto: "error"
  no-return-assign: "error"
  no-script-url: "error"
  no-self-compare: "error"
  no-sequences: "error"
  no-throw-literal: "error"
  no-unmodified-loop-condition: "error"
  no-unused-expressions: "error"
  no-useless-call: "error"
  no-useless-concat: "error"
  no-useless-escape: "error"
  no-warning-comments: "error"
  no-with: "error"
  radix: "error"
  wrap-iife: "error"
  yoda: "error"

  # Variables
  no-shadow: "error"
  no-undef: "error"
  no-undef-init: "error"
  no-use-before-define:
    - "error"
    -
      "functions": false # Allow function hoisting

  # CommonJS
  callback-return: "error"
  handle-callback-err:
    - "error"
    - "^.*(e|E)rr"

  # Style
  array-bracket-spacing: "error"
  block-spacing: "error"
  brace-style: "error"
  camelcase: "error"
  comma-spacing: "error"
  comma-style: "error"
  computed-property-spacing: "error"
  consistent-this:
    - "error"
    - "self"
  eol-last: "error"
  indent:
    - "error"
    - 2
  key-spacing: "error"
  keyword-spacing: "error"
  linebreak-style: "error"
  lines-around-comment: "error"
  max-depth: "error"
  max-statements-per-line: "error"
  new-cap: "error"
  new-parens: "error"
  newline-before-return: "error"
  no-bitwise: "error"
  no-continue: "error"
  no-lonely-if: "error"
  no-multiple-empty-lines:
    - "error"
    -
      "max": 1
  no-negated-condition: "error"
  no-nested-ternary: "error"
  no-spaced-func: "error"
  no-trailing-spaces: "error"
  no-unneeded-ternary: "error"
  no-whitespace-before-property: "error"
  object-property-newline: "error"
  operator-assignment: "error"
  operator-linebreak:
    - "error"
    - "after"
  quote-props:
    - "error"
    - "as-needed"
  quotes:
    - "error"
    - "single"
    -
      "avoidEscape": true
      "allowTemplateLiterals": true
  semi: "error"
  space-before-blocks: "error"
  space-before-function-paren:
    - "error"
    -
      "anonymous": "always"
      "named": "never"
  space-in-parens: "error"
  space-infix-ops: "error"
  space-unary-ops: "error"
  spaced-comment: "error"
  wrap-regex: "error"
